export const productsData = [
  {
    _id: Math.random(),
    name: "Wireless Headphones",
    description:
      "Noise-cancelling over-ear headphones with Bluetooth connectivity.",
    category: "Electronics",
    price: 99.99,
    image: "https://images.pexels.com/photos/3394654/pexels-photo-3394654.jpeg",
  },
  {
    _id: Math.random(),
    name: "Running Shoes",
    description: "Comfortable and lightweight shoes for everyday running.",
    category: "Footwear",
    price: 59.99,
    image: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg",
  },
  {
    _id: Math.random(),
    name: "Smartwatch",
    description: "Multifunctional smartwatch with health tracking features.",
    category: "Electronics",
    price: 89.95,
    image: "https://images.pexels.com/photos/3394654/pexels-photo-3394654.jpeg",
  },
  {
    _id: Math.random(),
    name: "Gaming Mouse",
    description: "Wired gaming mouse with customizable RGB lighting.",
    category: "Gaming",
    price: 29.99,
    image: "https://images.pexels.com/photos/1303090/pexels-photo-1303090.jpeg",
  },
  {
    _id: Math.random(),
    name: "Laptop Backpack",
    description: "Waterproof backpack with multiple compartments for laptops.",
    category: "Bags",
    price: 45.0,
    image: "https://images.pexels.com/photos/3394654/pexels-photo-3394654.jpeg",
  },
  {
    _id: Math.random(),
    name: "Portable Speaker",
    description: "Bluetooth speaker with loud stereo sound and deep bass.",
    category: "Electronics",
    price: 39.99,
    image: "https://images.pexels.com/photos/63703/pexels-photo-63703.jpeg",
  },
  {
    _id: Math.random(),
    name: "Yoga Mat",
    description: "Thick, non-slip yoga mat perfect for home workouts.",
    category: "Fitness",
    price: 24.99,
    image: "https://images.pexels.com/photos/3394654/pexels-photo-3394654.jpeg",
  },
  {
    _id: Math.random(),
    name: "Scented Candles",
    description: "Set of calming, aromatic candles for home ambiance.",
    category: "Home Decor",
    price: 22.99,
    image: "https://images.pexels.com/photos/3747787/pexels-photo-3747787.jpeg",
  },
  {
    _id: Math.random(),
    name: "Leather Wallet",
    description: "Compact RFID-blocking wallet made from genuine leather.",
    category: "Accessories",
    price: 21.95,
    image: "https://images.pexels.com/photos/322207/pexels-photo-322207.jpeg",
  },
  {
    _id: Math.random(),
    name: "Electric Kettle",
    description: "Fast boiling electric kettle with auto shut-off.",
    category: "Kitchen",
    price: 34.99,
    image: "https://images.pexels.com/photos/3394654/pexels-photo-3394654.jpeg",
  },
  {
    _id: Math.random(),
    name: "Face Moisturizer",
    description: "Hydrating and lightweight moisturizer for daily use.",
    category: "Beauty",
    price: 14.99,
    image: "https://images.pexels.com/photos/3736397/pexels-photo-3736397.jpeg",
  },
  {
    _id: Math.random(),
    name: "Wireless Keyboard",
    description: "Slim wireless keyboard for desktop and laptop computers.",
    category: "Electronics",
    price: 25.49,
    image: "https://images.pexels.com/photos/3394654/pexels-photo-3394654.jpeg",
  },
  {
    _id: Math.random(),
    name: "Digital Alarm Clock",
    description: "Modern LED alarm clock with dual alarm and snooze feature.",
    category: "Home",
    price: 18.75,
    image: "https://images.pexels.com/photos/1198264/pexels-photo-1198264.jpeg",
  },
  {
    _id: Math.random(),
    name: "Water Bottle",
    description: "Insulated stainless steel bottle for hot and cold drinks.",
    category: "Outdoors",
    price: 19.95,
    image: "https://images.pexels.com/photos/442153/pexels-photo-442153.jpeg",
  },
  {
    _id: Math.random(),
    name: "Dumbbell Set",
    description: "Adjustable dumbbells for home and gym workouts.",
    category: "Fitness",
    price: 69.99,
    image: "https://images.pexels.com/photos/669577/pexels-photo-669577.jpeg",
  },
  {
    _id: Math.random(),
    name: "Smartphone Stand",
    description: "Adjustable desk stand for phones and small tablets.",
    category: "Accessories",
    price: 12.49,
    image: "https://images.pexels.com/photos/5082565/pexels-photo-5082565.jpeg",
  },
  {
    _id: Math.random(),
    name: "Desk Lamp",
    description: "LED desk lamp with brightness adjustment and USB charging.",
    category: "Home Office",
    price: 27.99,
    image: "https://images.pexels.com/photos/374715/pexels-photo-374715.jpeg",
  },
  {
    _id: Math.random(),
    name: "Wireless Charger",
    description: "Fast charging pad compatible with all Qi-enabled devices.",
    category: "Electronics",
    price: 17.89,
    image: "https://images.pexels.com/photos/3394654/pexels-photo-3394654.jpeg",
  },
  {
    _id: Math.random(),
    name: "Portable Blender",
    description: "USB rechargeable blender for smoothies and shakes.",
    category: "Kitchen",
    price: 31.49,
    image: "https://images.pexels.com/photos/3394654/pexels-photo-3394654.jpeg",
  },
  {
    _id: Math.random(),
    name: "Action Camera",
    description: "Waterproof 4K action camera with image stabilization.",
    category: "Electronics",
    price: 79.99,
    image: "https://images.pexels.com/photos/3394654/pexels-photo-3394654.jpeg",
  },
  {
    _id: Math.random(),
    name: "Smartphone Stand",
    description: "Adjustable desk stand for phones and small tablets.",
    category: "Accessories",
    price: 12.49,
    image: "https://images.pexels.com/photos/5082565/pexels-photo-5082565.jpeg",
  },
];
